[package]
name = "solo"
version = "0.1.0"
authors = ["Mauricio Barrios <tiburinn@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.2.0"
indexmap = "1.8.0"